### ISSUE TITLE
How to add a generic type?

### ISSUE THREAD

**Issue by EuSouVoce** [A248/DazzleConf#45]
Hi, i need to add to the interface a type that represents an item from [XSeries.XItemStack](https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/XItemStack.java)

but adding the return type as Object does not work, this is the problematic interface:
```java
public interface EventItens {

    @Order(1)
    Boolean Enabled();

    @Order(2)

    Object Helmet();

    @Order(3)
    Object Chestplate();

    @Order(4)
    Object Leggings();

    @Order(5)
    Object Boots();

    @Order(6)
    Map<String, Object> Inventory();

}```

**Comment by EuSouVoce** [comment]
Example of config file:
```yaml
Itens: 
  Enabled: true 
  Helmet: 
    material: "DIAMOND_HELMET"
    damage: 0
    enchants:
      PROTECTION_ENVIRONMENTAL: 4
      DURABILITY: 4
  Chestplate:
    material: "DIAMOND_CHESTPLATE"
    damage: 0
    enchants:
      PROTECTION_ENVIRONMENTAL: 4
      DURABILITY: 4
  Leggings:
    material: "DIAMOND_LEGGINGS"
    damage: 0
    enchants:
      PROTECTION_ENVIRONMENTAL: 4
      DURABILITY: 4
  Boots:
    material: "DIAMOND_BOOTS"
    damage: 0
    enchants:
      PROTECTION_ENVIRONMENTAL: 4
      DURABILITY: 4
  Inventory:
    0: 
      material: "DIAMOND_SWORD"
      damage: 0
      enchants:
        DAMAGE_ALL: 5
    1: 
      material: "GOLDEN_APPLE"
      amount: 64
      damage: 1 
    2:
      material: "POTION"
      damage: 41 
      name: "&5Poção de Força"
      level: 2
      base-effect: "STRENGTH, false, false"
```
and another example:
```yaml
Itens:
  Enabled: true
  Armor:
    Helmet: {}
    Chestplate: {}
    Leggings: {}
    Boots: {}
  Inventory:
    '0': 
      material: WOOD_SWORD
      damage: 0
```
